spring.application.name=hupsteste

spring.datasource.url=jdbc:postgresql://localhost:5432/hups_teste
spring.datasource.username=postgres
spring.datasource.password=Ra28041996

# Mude de update para create-drop para limpar a estrutura antiga
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

